version: '2'
services:
    podcast_server:
        build: .
        volumes:
            - ./data:/root/code/data
        ports:
            - "80:8000"
        entrypoint: python main.py
        restart: unless-stopped
